version: 0.2

phases:
  build:
    commands:
      - java -version
      - mvn clean package -Ddb_user=${db_user} -Ddb_url=${db_url} -Ddb_pass=${db_pass}
artifacts:
  files:
    - 'Dockerfile'
    - target/e-commerce-0.0.1-SNAPSHOT.jar