server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  datasource:
    url: ${db_url}
    driver-class-name: org.postgresql.Driver
    username: ${db_user}
    password: ${db_pass}
  h2:
    console.enabled: true